# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpCMjxkg3w547ZuGlMsgwADlRNFulm9e
"""

# Colab 코드 실행 1/4: 데이터 로드 및 시계열 특징 생성 (인코딩 수정 버전)

import pandas as pd
import numpy as np
import json
import os
from datetime import timedelta

# --- 1. 파일 경로 정의 및 로드 ---
MAIN_DATA_PATH = "19_24_drunk.csv"
print("--- 1. 데이터 로드 시작 ---")

try:
    # ⚠️ 인코딩을 'cp949'로 수정 (UTF-8 디코딩 오류 해결)
    drunk_df = pd.read_csv(MAIN_DATA_PATH, encoding='cp949', sep=',')
    print(f"✅ 메인 사고 데이터 로드 성공: 총 {len(drunk_df)}건")
except FileNotFoundError:
    print(f"❌ 오류: '{MAIN_DATA_PATH}' 파일을 Colab에 업로드했는지 확인해주세요.")
    drunk_df = pd.DataFrame()
except Exception as e:
    # cp949도 실패할 경우 (매우 드물지만)
    print(f"❌ 데이터 로드 중 예상치 못한 오류 발생: {e}")
    drunk_df = pd.DataFrame()

if not drunk_df.empty:

    # --- 2. 기본 전처리 및 연도 특징 추출 ---
    print("\n--- 2. 기본 전처리 및 연도 특징 추출 ---")

    # '사고다발지id'에서 연도 추출 (예: 2022051 -> 2022)
    drunk_df['사고연도'] = drunk_df['사고다발지id'].astype(str).str[:4].astype(int)

    # '시도시군구명' 컬럼 분리 (예: '서울특별시 종로구1' -> '서울특별시', '종로구')
    drunk_df[['시도명', '구군명']] = drunk_df['시도시군구명'].str.split(' ', n=1, expand=True)
    drunk_df['구군명'] = drunk_df['구군명'].str.replace(r'\d+$', '', regex=True).str.strip()

    print(f"✅ '사고연도', '시도명', '구군명' 추출 완료.")

    # --- 3. 시계열 특징 공학 (Temporal Feature Engineering) ---
    print("\n--- 3. 시계열 특징 공학 (시간 정보 시뮬레이션) ---")

    # 🚨🚨🚨 중요: '사고일시' 컬럼 시뮬레이션 🚨🚨🚨
    np.random.seed(42)

    start_time = pd.to_datetime('2019-01-01')
    time_range_seconds = (pd.to_datetime('2024-12-31') - start_time).total_seconds()
    random_seconds = np.random.randint(0, time_range_seconds, size=len(drunk_df))
    drunk_df['사고일시'] = start_time + pd.to_timedelta(random_seconds, unit='s')

    print(f"✅ '사고일시' 컬럼 임시 생성 완료.")

    # 3-1. 요일 및 주말/주중 구분
    drunk_df['요일'] = drunk_df['사고일시'].dt.dayofweek # 0:월, 6:일
    drunk_df['주말_여부'] = drunk_df['요일'].apply(lambda x: 1 if x >= 5 else 0) # 토/일 = 1 (주말)

    # 3-2. 시간대(피크타임) 특징 추출
    drunk_df['시간대'] = drunk_df['사고일시'].dt.hour

    # 음주운전 위험 피크 시간대 분류 (22시 ~ 새벽 4시를 고위험으로 설정)
    def classify_peak_time(hour):
        if 22 <= hour or hour <= 4:
            return '심야/새벽_피크'
        elif 18 <= hour < 22:
            return '저녁_피크'
        else:
            return '주간/비피크'

    drunk_df['위험_시간대_그룹'] = drunk_df['시간대'].apply(classify_peak_time)

    # --- 4. 중간 결과 저장 ---
    # 다음 단계(공간 특징 공학)에서 사용하기 위해 저장합니다.
    drunk_df.to_pickle("processed_part1_df.pkl")
    print("\n✅ Part 1 완료. 중간 결과가 'processed_part1_df.pkl'로 저장되었습니다.")

# Colab 코드 실행 2/4: 공간 특징 생성

import pandas as pd
import numpy as np
import json
# Colab 환경에서 shapely 라이브러리가 기본으로 설치되어 있습니다.
from shapely.geometry import Polygon
from math import radians, sin, cos, sqrt, atan2

# --- 1. Part 1 결과 로드 ---
try:
    df = pd.read_pickle("processed_part1_df.pkl")
    print("✅ Part 1 결과 로드 성공.")
except FileNotFoundError:
    print("❌ 오류: 'processed_part1_df.pkl' 파일을 찾을 수 없습니다. Part 1 코드를 먼저 실행해주세요.")
    df = pd.DataFrame()

if not df.empty:

    print("\n--- 2. 공간 특징 공학 시작 ---")

    # 2-1. 위도/경도 데이터 타입 변환 및 결측치 처리
    df['경도'] = pd.to_numeric(df['경도'], errors='coerce')
    df['위도'] = pd.to_numeric(df['위도'], errors='coerce')
    df.dropna(subset=['경도', '위도'], inplace=True)
    print(f"✅ 경도/위도 결측치 처리 완료. (남은 데이터: {len(df)}건)")


    # 2-2. 특징 1: 다발지역 폴리곤 면적 계산 (지리적 크기 특징)
    def calculate_polygon_area(json_str):
        """다발지역 폴리곤 JSON 문자열을 파싱하여 면적(m^2)을 추정합니다."""
        try:
            data = json.loads(json_str)
            coords = data['coordinates'][0]
            polygon = Polygon(coords)
            # WGS84 좌표계에서의 면적을 m^2으로 대략 환산 (특징으로 활용)
            # 1도 경도/위도당 대략 111km이므로 (111000m)^2을 곱하여 근사치 계산
            return polygon.area * (111000**2)
        except Exception:
            return 0.0

    df['폴리곤_면적_m2'] = df['다발지역폴리곤'].apply(calculate_polygon_area)
    print("✅ 특징 1: '폴리곤_면적_m2' 생성 완료.")


    # 2-3. 특징 2: 공간 밀집도 지수 (최근접 다발지역 거리) 계산

    # Haversine 공식 (두 지점 간 거리(km) 계산)
    def haversine(lat1, lon1, lat2, lon2):
        R = 6371  # 지구 반지름 (km)
        lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
        dlon = lon2 - lon1
        dlat = lat2 - lat1
        a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
        c = 2 * atan2(sqrt(a), sqrt(1 - a))
        return R * c

    def find_nearest_distance(row, df):
        """가장 가까운 다발지역까지의 거리(km)를 찾습니다. (자기 자신 제외)"""
        distances = []
        # 자기 자신을 제외한 나머지 데이터
        other_locations = df[df.index != row.name]

        # NOTE: 대규모 데이터셋에서는 이 계산이 매우 오래 걸릴 수 있으므로,
        # 실전에서는 K-D Tree나 Geohash를 사용한 최적화가 필요합니다.
        # 여기서는 정확한 특징값 계산을 위해 전체 데이터를 사용합니다.
        for index, other_row in other_locations.iterrows():
            dist = haversine(row['위도'], row['경도'], other_row['위도'], other_row['경도'])
            distances.append(dist)

        return min(distances) if distances else 0.0

    print("\n⏳ 특징 2: '최근접_다발지역_거리_km' 계산 중...")
    df['최근접_다발지역_거리_km'] = df.apply(
        lambda row: find_nearest_distance(row, df), axis=1
    )
    print("✅ 특징 2: '최근접_다발지역_거리_km' 계산 완료.")


    # --- 3. 최종 데이터 저장 ---
    # 모든 특징 공학이 완료된 최종 데이터프레임 저장
    df.to_pickle("final_processed_df.pkl")

    print("\n--- Part 2 최종 결과 확인 (상위 5개 행) ---")
    print(df[['사고건수', '폴리곤_면적_m2', '최근접_다발지역_거리_km', '위험_시간대_그룹']].head())
    print("\n✅ 1단계 특징 공학 완료. 최종 데이터가 'final_processed_df.pkl'로 저장되었습니다.")

# Colab 코드 실행 3/4: 모델링 준비 (인코딩 및 데이터 분할)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# --- 1. 최종 전처리된 데이터 로드 ---
try:
    df = pd.read_pickle("final_processed_df.pkl")
    print("✅ 'final_processed_df.pkl' 로드 성공.")
except FileNotFoundError:
    print("❌ 오류: 'final_processed_df.pkl' 파일을 찾을 수 없습니다. Part 2 코드를 먼저 실행해주세요.")
    df = pd.DataFrame()

if not df.empty:

    # --- 2. 목표 변수(Target Y) 정의: 위험 등급 분류 ---
    print("\n--- 2. 목표 변수(Target Y) 정의: 사고건수 -> 위험 등급 분류 ---")

    # 사고건수의 분위수를 기준으로 위험 등급 경계 설정 (3분위수 사용)
    # Q1 (33% 경계), Q2 (66% 경계)
    quantiles = df['사고건수'].quantile([0.33, 0.66]).tolist()
    q1, q2 = quantiles[0], quantiles[1]

    def classify_risk(count):
        if count >= q2:
            return 2 # '고위험' (High Risk)
        elif count >= q1:
            return 1 # '중위험' (Medium Risk)
        else:
            return 0 # '저위험' (Low Risk)

    df['위험_등급'] = df['사고건수'].apply(classify_risk)

    print(f"✅ 위험 등급 분류 기준: Q1({q1:.2f}), Q2({q2:.2f})")
    print("✅ 위험 등급 분포:\n{}".format(df['위험_등급'].value_counts()))


    # --- 3. 특징(Feature X) 및 목표 변수 분리 ---
    features = [
        '사고연도', '주말_여부', '위험_시간대_그룹',
        '경도', '위도', '폴리곤_면적_m2',
        '최근접_다발지역_거리_km', '시도명', '구군명'
    ]

    X = df[features]
    Y = df['위험_등급']


    # --- 4. 범주형 특징 원-핫 인코딩 (One-Hot Encoding) ---
    print("\n--- 4. 범주형 특징 원-핫 인코딩 시작 ---")

    # 원-핫 인코딩을 적용할 범주형 컬럼 정의
    categorical_cols = ['위험_시간대_그룹', '시도명', '구군명']

    # One-Hot Encoding 적용 (다중공선성 방지를 위해 drop_first=True)
    X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

    print(f"✅ 원-핫 인코딩 완료. 특징 수 증가: {X.shape[1]} -> {X_encoded.shape[1]}")

    # --- 5. 데이터 분할 (훈련/테스트) ---
    print("\n--- 5. 데이터 분할 (Train/Test Split) ---")

    # Stratify=Y 옵션을 사용하여 위험 등급의 비율이 훈련/테스트 세트에 동일하게 분포되도록 합니다.
    X_train, X_test, Y_train, Y_test = train_test_split(
        X_encoded, Y, test_size=0.2, random_state=42, stratify=Y
    )

    # --- 6. 다음 단계를 위해 데이터 저장 ---
    X_train.to_pickle("X_train.pkl")
    X_test.to_pickle("X_test.pkl")
    Y_train.to_pickle("Y_train.pkl")
    Y_test.to_pickle("Y_test.pkl")

    print(f"✅ 데이터 분할 완료. 훈련 세트 크기: {len(X_train)}건")
    print("✅ 모델링 준비 완료. 훈련/테스트 데이터가 저장되었습니다.")

import pandas as pd
import numpy as np
import os
import re # 정규표현식 사용을 위해 import 추가

# =================================================================
# Part 4: 시도/구군 코드 로드, 정리 및 병합 (Excel Sheet 사용)
# =================================================================

print("\n--- 4. 시도/구군 코드 로드 및 정리 시작 (Excel Sheet 사용) ---")

# 1. 런타임 재시작으로 사라진 df를 pickle 파일에서 다시 로드
try:
    df = pd.read_pickle("final_processed_df.pkl")
    print("✅ 'final_processed_df.pkl' 로드 성공. (df 변수 재정의)")
except FileNotFoundError:
    print("❌ 오류: 'final_processed_df.pkl' 파일을 찾을 수 없습니다. 이전 Part 코드를 먼저 실행해 주세요.")
    df = pd.DataFrame()
    if df.empty:
        raise NameError("메인 데이터프레임(df)을 로드할 수 없어 작업을 중단합니다. 이전 단계를 다시 실행해 주세요.")
except Exception as e:
    print(f"❌ 데이터 로드 중 예상치 못한 오류 발생: {e}")
    raise NameError("메인 데이터프레임(df) 로드 실패로 작업을 중단합니다.")


# 🚨🚨🚨 핵심 수정: 단일 Excel 파일과 Sheet Name 사용 🚨🚨🚨
CODE_FILE = 'AccidentHazard_CodeList.xlsx'
SIDO_SHEET = 'Sido 요청값'
GUGUN_SHEET = 'Gugun 요청값'

# 시도명 표준화 맵핑 (길이 긴 이름 -> 짧은 이름)
sido_std_mapping = {
    '서울특별시': '서울', '부산광역시': '부산', '대구광역시': '대구', '인천광역시': '인천',
    '광주광역시': '광주', '대전광역시': '대전', '울산광역시': '울산', '세종특별자치시': '세종',
    '경기도': '경기', '강원특별자치도': '강원', '강원도': '강원', '충청북도': '충북',
    '충청남도': '충남', '전라북도': '전북', '전라남도': '전남', '경상북도': '경북',
    '경상남도': '경남', '제주특별자치도': '제주'
}

# ⭐⭐⭐ 구군명 표준화 함수 수정 (가장 세부적인 구/군/시 명칭만 추출) ⭐⭐⭐
# '수원시 권선구' -> '권선구' 처럼 가장 세부적인 행정구역 명칭만 남깁니다.
def standardize_gugun(gugun_name):
    gugun_name = str(gugun_name).strip()

    # 1. 괄호와 그 내용 제거 (예: '수원시(장안구)' -> '수원시')
    gugun_name = gugun_name.split('(')[0].strip()

    # 2. '시' + '구' 형태에서 '구'만 추출 (예: '수원시 권선구' -> '권선구')
    # 단, '군' 또는 '시'가 단독으로 나오는 경우는 제외
    parts = gugun_name.split()
    if len(parts) > 1 and parts[-1].endswith(('구', '군', '읍', '면', '동', '가', '로', '길')):
        # 가장 마지막의 세부 행정구역 명칭을 사용 (예: '수원시 권선구' -> '권선구')
        return parts[-1]

    # 3. 그 외 (예: '수원시', '철원군' 등)
    return gugun_name

# -------------------------------------------------------------------------
# 파일 로드 및 정리 (이전 로직 유지)
# -------------------------------------------------------------------------

if not os.path.exists(CODE_FILE):
    print(f"❌ 오류: '{CODE_FILE}' 파일을 Colab에 업로드했는지 확인해주세요.")
    df_sido_code = pd.DataFrame(columns=['시도명_std', 'sido_cd'])
    df_gugun_code = pd.DataFrame(columns=['시도_std', '구군명_std', 'gugun_cd'])
else:
    # 2. 시도 코드 (Sheet 1) 로드 및 정리
    try:
        df_sido_code = pd.read_excel(CODE_FILE, sheet_name=SIDO_SHEET, header=None)
        df_sido_code = df_sido_code.iloc[1:][[0, 1]].copy()
        df_sido_code.columns = ['시도명_raw', 'sido_cd']

        df_sido_code = df_sido_code.dropna(subset=['sido_cd'])
        df_sido_code['sido_cd'] = df_sido_code['sido_cd'].astype(str).str.strip()
        df_sido_code['시도명_raw'] = df_sido_code['시도명_raw'].astype(str).str.strip()

        df_sido_code['시도명_std'] = df_sido_code['시도명_raw'].replace(sido_std_mapping, regex=True)

        print(f"✅ 시도 코드 로드 및 정리 완료. (총 {len(df_sido_code)}개 시도 코드)")

    except Exception as e:
        print(f"❌ 시도 코드 로드 중 오류 발생 (시트명 '{SIDO_SHEET}' 확인): {e}")
        df_sido_code = pd.DataFrame(columns=['시도명_std', 'sido_cd'])

    # 3. 구군 코드 (Sheet 2) 로드 및 정리
    try:
        df_gugun_code = pd.read_excel(CODE_FILE, sheet_name=GUGUN_SHEET, header=None)
        df_gugun_code = df_gugun_code.iloc[1:][[0, 1, 2]].copy()
        df_gugun_code.columns = ['시도_raw', '구군명_raw', 'gugun_cd']

        df_gugun_code['시도_raw'] = df_gugun_code['시도_raw'].ffill()
        df_gugun_code = df_gugun_code.dropna(subset=['gugun_cd'])
        df_gugun_code['gugun_cd'] = df_gugun_code['gugun_cd'].astype(str).str.strip()

        # 시도명 표준화
        df_gugun_code['시도_std'] = df_gugun_code['시도_raw'].replace(sido_std_mapping, regex=True).str.strip()

        # 구군명 표준화: 코드 파일에도 표준화 함수 적용
        df_gugun_code['구군명_std'] = df_gugun_code['구군명_raw'].apply(standardize_gugun)

        print(f"✅ 구군 코드 로드 및 정리 완료. (총 {len(df_gugun_code)}개 구군 코드)")

    except Exception as e:
        print(f"❌ 구군 코드 로드 중 오류 발생 (시트명 '{GUGUN_SHEET}' 확인): {e}")
        df_gugun_code = pd.DataFrame(columns=['시도_std', '구군명_std', 'gugun_cd'])


# -------------------------------------------------------------------------
# 메인 데이터프레임 표준화 및 병합
# -------------------------------------------------------------------------

if not df.empty:
    # 1. 메인 데이터프레임 (df)의 병합 키 표준화
    df['시도명_std'] = df['시도명'].replace(sido_std_mapping, regex=True).str.strip()

    # ⭐⭐ 메인 데이터프레임의 구군명에 표준화 함수 적용 (핵심) ⭐⭐
    df['구군명_std'] = df['구군명'].apply(standardize_gugun)

    print("✅ 메인 데이터프레임의 병합 키 표준화 완료.")

    # 2. 시도 코드 병합 (이전 sido_cd 컬럼 제거 후)
    if not df_sido_code.empty:
        if 'sido_cd' in df.columns: df = df.drop(columns=['sido_cd'])
        df = pd.merge(df, df_sido_code[['시도명_std', 'sido_cd']], on='시도명_std', how='left')
        print("✅ 시도 코드 병합 완료. (키: 시도명_std)")
    else:
        print("⚠️ 경고: 시도 코드 데이터 로드 실패로 시도 코드 병합을 건너뜁니다.")
        df['sido_cd'] = np.nan

    # 3. 구군 코드 병합 (이전 gugun_cd 컬럼 및 임시 컬럼 제거 후)
    if not df_gugun_code.empty:
        if 'gugun_cd' in df.columns: df = df.drop(columns=['gugun_cd'])
        if '시도_std' in df.columns: df = df.drop(columns=['시도_std'])

        df = pd.merge(df, df_gugun_code[['시도_std', '구군명_std', 'gugun_cd']],
                     left_on=['시도명_std', '구군명_std'],
                     right_on=['시도_std', '구군명_std'],
                     how='left')

        if '시도_std' in df.columns:
            df = df.drop(columns=['시도_std'])

        print("✅ 구군 코드 병합 완료. (키: 시도명_std, 구군명_std)")

        # 4. 결과 확인
        print("\n✅ 코드 병합 완료. 결과 DataFrame 샘플:")
        print(df[['시도명', '구군명', '시도명_std', '구군명_std', 'sido_cd', 'gugun_cd']].head())

        missing_sido_cd = df['sido_cd'].isnull().sum()
        missing_gugun_cd = df['gugun_cd'].isnull().sum()

        print(f"\n💡 병합 후 확인 사항:")
        print(f"   - sido_cd 누락 개수: {missing_sido_cd}개")
        print(f"   - gugun_cd 누락 개수: {missing_gugun_cd}개")

        if missing_sido_cd > 0 or missing_gugun_cd > 0:
            print("⚠️ 경고: 표준화 및 디버깅 후에도 일부 매핑이 누락되었습니다. (데이터 불일치 발생 지점 분석 필요)")
            # 5. 누락된 데이터를 확인하기 위한 샘플 출력 (디버깅)
            print("\n❌ 누락된 데이터 5개 샘플 (디버깅용):")
            # sido_cd 또는 gugun_cd가 누락된 데이터
            print(df[df['sido_cd'].isnull() | df['gugun_cd'].isnull()][['시도명', '구군명', '시도명_std', '구군명_std']].head())

        else:
            print("🎉 모든 데이터에 대해 sido_cd 및 gugun_cd 매핑 성공!")

        # 6. 다음 단계를 위해 Part 4에서 코드 병합이 완료된 df를 저장합니다.
        df = df.drop(columns=['시도명_std', '구군명_std'], errors='ignore')
        df.to_pickle("processed_part4_df.pkl")
        print("\n✅ Part 4 완료. 중간 결과가 'processed_part4_df.pkl'로 저장되었습니다.")
    else:
        print("⚠️ 경고: 구군 코드 데이터 로드 실패로 구군 코드 병합을 건너뜁니다.")
else:
    print("❌ 치명적 오류: 메인 데이터프레임(df)이 로드되지 않아 Part 4를 완료할 수 없습니다.")
# =================================================================

import pandas as pd
import geopandas as gpd
import json
import re
from IPython.display import HTML, display

# --- 1. 파일 경로 설정 ---
# **사용자 파일 경로로 수정하세요**
# GeoJSON 파일 경로 (예: 시군구 경계 데이터)
sig_geo_path = 'korea_geojson.json' # 사용자 환경에 맞는 정확한 경로와 파일명을 사용하세요.
accident_csv_path = '19_24_drunk.csv'

# --- 2. 데이터 로드 및 전처리 ---

# 사고 데이터 로드 (더 강력한 인코딩 처리: utf-8-sig -> cp949 순차 시도)
accident_df = pd.DataFrame()
try:
    print("데이터 로드 시도 (1/3): 'utf-8-sig' 인코딩으로 CSV 로드...")
    accident_df = pd.read_csv(accident_csv_path, encoding='utf-8-sig')
except UnicodeDecodeError:
    try:
        print("데이터 로드 시도 (2/3): 'utf-8-sig' 실패. 'cp949' 인코딩으로 CSV 로드...")
        accident_df = pd.read_csv(accident_csv_path, encoding='cp949')
    except UnicodeDecodeError:
        print("❌ 치명적 오류: 사고 데이터 파일의 인코딩을 해석할 수 없습니다. 'utf-8-sig'와 'cp949' 모두 실패했습니다.")
    except FileNotFoundError:
        print(f"❌ 치명적 오류: 사고 데이터 파일 '{accident_csv_path}'을 찾을 수 없습니다. 경로를 확인하세요.")
except FileNotFoundError:
    print(f"❌ 치명적 오류: 사고 데이터 파일 '{accident_csv_path}'을 찾을 수 없습니다. 경로를 확인하세요.")


if accident_df.empty:
    geojson_with_risk_scores = json.dumps({"type": "FeatureCollection", "features": []})
    point_data_for_html = json.dumps({'points': []})
    print("⚠️ 데이터 처리 중단: 사고 데이터 로드 실패로 빈 지도를 출력합니다.")
else:
    print(f"✅ 데이터 로드 성공: 총 {len(accident_df)}건의 사고 데이터.")

    # 필수 컬럼 리스트 (실제 데이터 헤더에 맞게 수정됨)
    required_cols = ['시도시군구명', '사고건수', '사상자수', '위도', '경도', '지점명']

    # 필수 컬럼 확인 및 추출
    for col in required_cols:
        if col not in accident_df.columns:
            raise KeyError(f"❌ 오류: 사고 데이터에 필수 컬럼 '{col}'이(가) 누락되었습니다. 실제 데이터 헤더를 확인하세요.")

    accident_df = accident_df[required_cols].copy()
    accident_df['사고건수'] = pd.to_numeric(accident_df['사고건수'], errors='coerce').fillna(0).astype(int)

    # 지리 데이터 로드 (GeoPandas 사용)
    try:
        print(f"데이터 로드 시도 (3/3): GeoJSON 파일 ('{sig_geo_path}') 로드...")
        # GeoJSON 파일 로드. 인코딩 문제 방지를 위해 utf-8-sig 사용
        gdf = gpd.read_file(sig_geo_path, encoding='utf-8-sig')
    except Exception as e:
        raise Exception(f"❌ 치명적 오류: GeoJSON 로드 실패. 경로를 확인하세요: {sig_geo_path}. 오류: {e}")

    # --- 3. 위험 점수 계산 및 GeoJSON에 병합 ---

    # GeoJSON 파일은 보통 시/군/구 이름만 포함하므로, 사고 데이터에서 시/도 이름을 제거하고 마지막 이름만 추출합니다.
    def extract_gugun_name(full_name):
        # 숫자 제거 및 공백 제거
        clean_name = re.sub(r'\d+', '', full_name).strip()
        # 공백으로 나눈 뒤 마지막 요소 (시, 군, 구 이름)를 반환
        parts = clean_name.split()
        return parts[-1] if parts else clean_name

    accident_df['SIG_KOR_NM'] = accident_df['시도시군구명'].apply(extract_gugun_name)

    # 지역별 총 사고 건수 계산 (위험 점수)
    risk_scores = accident_df.groupby('SIG_KOR_NM')['사고건수'].sum().reset_index()
    risk_scores.rename(columns={'사고건수': 'risk_score'}, inplace=True)

    # GeoDataFrame에 위험 점수 병합 (left join)
    if 'SIG_KOR_NM' not in gdf.columns:
        print("⚠️ 경고: GeoJSON 파일에 'SIG_KOR_NM' 컬럼이 없습니다. GeoJSON 헤더를 확인하여 병합 키를 수정해야 합니다.")
        geojson_with_risk_scores = gdf.to_json()
    else:
        gdf_merged = gdf.merge(risk_scores, on='SIG_KOR_NM', how='left')
        gdf_merged['risk_score'] = gdf_merged['risk_score'].fillna(0) # 사고 없는 지역은 0으로 채움
        geojson_with_risk_scores = gdf_merged.to_json()


    # --- 4. 포인트 데이터 준비 ---

    # 위도/경도 정보를 가진 리스트로 변환
    point_data_list = accident_df[['위도', '경도', '사고건수', '사상자수', '지점명']].to_dict('records')
    point_data_for_html = json.dumps({'points': point_data_list})

# --- 5. HTML 템플릿 및 데이터 삽입 ---

# JSON 데이터를 JavaScript 변수에 직접 삽입할 수 있도록 문자열화
def escape_for_js_literal(data_str):
    data_str = data_str.replace('\\', '\\\\')
    data_str = data_str.replace("'", "\\'")
    return data_str

geojson_str = escape_for_js_literal(geojson_with_risk_scores)
point_data_str = escape_for_js_literal(point_data_for_html)

# HTML 템플릿 (f-string 오류 방지를 위해 모든 중괄호는 {{}}로 처리됨)
html_template = f"""
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>음주운전 사고 다발 지역 위험 지도</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Tailwind CSS (Aesthetics) -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">

    <!-- Leaflet JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20n6n+A4+B0sP1H0/4P3+xQW966/p19O/T91/4w7/c0="
            crossorigin=""></script>

    <style>
        /* 기본 폰트 설정 */
        body {{
            font-family: 'Inter', 'Noto Sans KR', sans-serif;
            background-color: #f3f4f6;
        }}
        /* 지도 컨테이너 스타일 */
        #map {{
            height: 80vh; /* 높이 유지 */
            width: 100%;
            border-radius: 0.75rem; /* rounded-xl */
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05); /* shadow-xl */
            margin-top: 1.5rem;
        }}
        /* 범례 및 정보창 스타일 */
        .info {{
            padding: 10px 15px;
            font: 14px/18px Arial, Helvetica, sans-serif;
            background: white;
            background: rgba(255,255,255,0.95);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
            border-radius: 0.5rem; /* rounded-lg */
        }}
        .legend {{
            line-height: 20px;
            color: #555;
        }}
        .legend i {{
            width: 18px;
            height: 18px;
            float: left;
            margin-right: 8px;
            opacity: 0.9;
            border-radius: 3px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1); /* 범례 색상 블록에 그림자 추가 */
        }}
        .status-box {{
            padding: 12px;
            border-radius: 0.5rem;
            margin-bottom: 15px;
            text-align: center;
            font-weight: 700;
            transition: background-color 0.3s;
            border: 1px solid;
        }}
        .leaflet-popup-content-wrapper {{
            border-radius: 0.5rem;
            padding: 0;
            line-height: 1.5;
        }}
        .leaflet-popup-content {{
            margin: 10px;
        }}
    </style>
</head>
<body class="p-4 sm:p-8">
    <div class="container mx-auto max-w-7xl">
        <div class="text-center mb-6 bg-white p-4 rounded-lg shadow-md">
            <h1 class="text-3xl sm:text-4xl font-extrabold text-red-700">🚨 음주운전 사고 위험 지역 지도 🍺</h1>
            <p class="text-gray-600 mt-2 text-sm sm:text-base">지역별 사고 건수 기반 위험도 (면적색) 및 개별 사고 지점 (원형 마커) 시각화</p>
        </div>

        <div id="status-message" class="status-box border-blue-400 bg-blue-50 text-blue-800">
            데이터 로드 및 지도 초기화 중...
        </div>

        <div id="map">
            <!-- Leaflet Map Will Be Rendered Here -->
        </div>
    </div>

    <script>
        // --- 1. Python에서 삽입된 데이터를 JavaScript 변수에 할당 ---
        const MAP_DATA = JSON.parse('{geojson_str}');
        const POINT_DATA = JSON.parse('{point_data_str}');

        const TILE_URL = 'https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png';

        // DOM 요소 가져오기
        const statusMessage = document.getElementById('status-message');

        // Leaflet 맵 인스턴스를 저장할 변수
        let map;
        let geoJsonLayer;

        // 위험 점수 색상을 결정하는 함수 (Choropleth Map용)
        function getColor(d) {{
            // 점수에 따라 7단계 색상 정의 (붉은 계열)
            return d > 100 ? '#800026' :
                   d > 50  ? '#BD0026' :
                   d > 20  ? '#E31A1C' :
                   d > 10  ? '#FC4E2A' :
                   d > 5   ? '#FD8D3C' :
                   d > 0   ? '#FEB24C' :
                             '#FFEDA0'; // 0점
        }}

        // 지리적 특성(Feature)의 스타일을 지정하는 함수
        function style(feature) {{
            // GeoJSON에 'risk_score'가 추가되어 있다고 가정
            const risk = feature.properties.risk_score || 0;

            return {{
                fillColor: getColor(risk),
                weight: 1,
                opacity: 1,
                color: 'white',
                dashArray: '3',
                fillOpacity: 0.7
            }};
        }}

        // 마우스 오버 시 이벤트 처리 (하이라이트)
        function highlightFeature(e) {{
            const layer = e.target;

            layer.setStyle({{
                weight: 5,
                color: '#666',
                dashArray: '',
                fillOpacity: 0.9
            }});

            // 💥 수정 1: 마우스 오버 시 폴리곤을 맨 앞으로 가져오는 코드를 제거했습니다.
            // if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {{
            //     layer.bringToFront();
            // }}

            info.update(layer.feature.properties);
        }}

        // 마우스 아웃 시 이벤트 처리 (원래 스타일로 복원)
        function resetHighlight(e) {{
            if (geoJsonLayer) {{
                 geoJsonLayer.resetStyle(e.target);
            }}
            info.update();
        }}

        // 각 Feature에 이벤트를 바인딩
        function onEachFeature(feature, layer) {{
            layer.on({{
                mouseover: highlightFeature,
                mouseout: resetHighlight,
                click: function(e) {{
                    const props = feature.properties;
                    // GeoJSON에 'SIG_KOR_NM' 또는 'NAME'이 있다고 가정
                    const name = props.SIG_KOR_NM || props.NAME || '지역명 없음';
                    const popupContent = `
                        <div class="p-2 font-sans">
                            <h4 class="text-base font-bold text-red-700 mb-1">${{name}}</h4>
                            <p class="text-sm">위험 점수 (사고 건수 합):
                                <span class="font-extrabold text-xl text-red-600">${{props.risk_score ? parseFloat(props.risk_score).toFixed(1) : '0'}}</span> 점
                            </p>
                        </div>
                    `;
                    layer.bindPopup(popupContent).openPopup();
                }}
            }});
        }}


        // 개별 사고 지점에 마커를 추가하는 함수 (Point Marker)
        function addPointMarkers() {{
            statusMessage.innerHTML = '개별 사고 지점 마커 추가 중...';

            // POINT_DATA 변수를 직접 사용
            const points = POINT_DATA.points || [];

            const markers = points.map(point => {{
                const lat = parseFloat(point['위도']);
                const lng = parseFloat(point['경도']);

                if (isNaN(lat) || isNaN(lng) || lat === 0 || lng === 0) {{
                    return null;
                }}

                const accidentCount = parseInt(point['사고건수'], 10) || 1;
                const radius = Math.log(accidentCount + 1) * 3 + 3;

                const markerColor = accidentCount > 10 ? '#4a148c' :
                                    accidentCount > 3 ? '#880e4f' :
                                                        '#ad1457';

                const marker = L.circleMarker([lat, lng], {{
                    radius: radius,
                    color: '#ffffff',
                    weight: 1,
                    opacity: 0.8,
                    fillColor: markerColor,
                    fillOpacity: 0.8
                }});

                // 마커의 클릭 이벤트가 GeoJSON으로 전파되는 것을 막음 (추가 안정성)
                marker.on('click', function(e) {{
                    L.DomEvent.stopPropagation(e);
                }});

                const popupContent = `
                    <div class="font-sans text-sm p-1">
                        <div class="font-extrabold text-base text-purple-800 text-center mb-1">
                            ${{point['지점명'] || '이름 없음'}}
                        </div>
                        <div class="text-xs text-gray-700">
                            사고 건수: <span class="font-semibold text-purple-600">${{point['사고건수']}}</span> 건
                        </div>
                        <div class="text-xs text-gray-600">
                            사상자 수: <span class="font-semibold">${{point['사상자수']}}</span> 명
                        </div>
                    </div>
                `;
                marker.bindPopup(popupContent, {{ closeButton: true, maxWidth: 250 }});

                marker.bindTooltip(`사고 ${{point['사고건수']}}건 (${{point['지점명']}})`, {{
                    permanent: false,
                    direction: 'top',
                    offset: [0, -radius]
                }});

                return marker;
            }}).filter(m => m !== null);

            const markerLayer = L.layerGroup(markers);
            markerLayer.addTo(map);

            console.log(`✅ Point Markers Added: 총 ${{markers.length}}개 유효 지점.`);
        }}

        // 정보창 (Info Control) 정의 및 초기화
        let info = L.control({{ position: 'topright' }});

        info.onAdd = function (map) {{
            this._div = L.DomUtil.create('div', 'info');
            this.update();
            return this._div;
        }};

        info.update = function (props) {{
            const name = props ? (props.SIG_KOR_NM || props.NAME || '알 수 없는 지역') : '지역을 올려보세요';
            const risk = props && props.risk_score !== undefined ? parseFloat(props.risk_score).toFixed(1) : 'N/A';

            this._div.innerHTML = '<h4>음주운전 사고 위험 점수 (면적)</h4>' +
                (props ?
                '<b>' + name + '</b><br />' + '위험 점수: <b>' + risk + '</b> 점'
                : '지역을 지도 위에서 선택하세요');
        }};

        // 범례 추가 함수
        function addLegend() {{
            const legend = L.control({{ position: 'bottomright' }});

            legend.onAdd = function (map) {{
                const div = L.DomUtil.create('div', 'info legend');
                const grades = [0, 5, 10, 20, 50, 100];
                const labels = ['<strong>사고 위험 점수 (면적)</strong>'];
                let from, to;

                for (let i = 0; i < grades.length; i++) {{
                    from = grades[i];
                    to = grades[i + 1];

                    labels.push(
                        '<i style="background:' + getColor(from + 1) + '"></i> ' +
                        from + (to ? (to === 100 ? '&ndash;100' : '&ndash;' + to) : '+'));
                }}

                labels.push('<br><strong>개별 지점 마커 (원)</strong>');
                labels.push('<i style="background:#4a148c; border: 1px solid #fff;"></i> 사고 10건 이상');
                labels.push('<i style="background:#880e4f; border: 1px solid #fff;"></i> 사고 4~10건');
                labels.push('<i style="background:#ad1457; border: 1px solid #fff;"></i> 사고 1~3건');


                div.innerHTML = labels.join('<br>');
                return div;
            }};

            legend.addTo(map);
        }}

        // 맵 데이터 로드 및 처리 메인 함수
        function loadAndDisplayMapData() {{
            console.log("⭐ 지오맵 초기화 함수 시작");

            map = L.map('map').setView([36.5, 127.8], 7);

            L.tileLayer(TILE_URL, {{
                maxZoom: 18,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }}).addTo(map);

            info.addTo(map);

            try {{
                // 1. GeoJSON (Choropleth Map) 데이터 로드 (Python에서 삽입된 변수 사용)
                statusMessage.innerHTML = 'GeoJSON 데이터 로드 및 Choropleth 맵 생성 중...';

                const geoJsonData = MAP_DATA;

                if (!geoJsonData || geoJsonData.type !== 'FeatureCollection') {{
                    throw new Error("GeoJSON 데이터가 유효한 'FeatureCollection' 형식이 아닙니다. Python 코드를 확인하세요.");
                }}

                // 2. GeoJSON 레이어 추가
                geoJsonLayer = L.geoJson(geoJsonData, {{
                    style: style,
                    onEachFeature: onEachFeature
                }}).addTo(map);

                // GeoJSON 레이어를 명시적으로 가장 아래로 보냅니다. (기본 설정)
                geoJsonLayer.bringToBack();

                try {{
                    map.fitBounds(geoJsonLayer.getBounds());
                }} catch (e) {{
                    console.warn("지도 경계 설정 실패. 기본 뷰를 사용합니다.", e);
                }}
                console.log("✅ GeoJSON Choropleth 맵 생성 완료.");


                // 3. 개별 지점 마커 추가 (Point Marker)
                // 마커는 이 레이어보다 후에 추가되므로 자동으로 위에 위치하며,
                // GeoJSON의 bringToFront 기능이 제거되었으므로 마커 클릭이 방해받지 않습니다.
                addPointMarkers();


                // 4. 범례 추가
                addLegend();

                // 5. 최종 상태 메시지 업데이트
                statusMessage.style.backgroundColor = '#d1fae5';
                statusMessage.style.borderColor = '#6ee7b7';
                statusMessage.style.color = '#065f46';
                statusMessage.innerHTML = '🎉 지도 시각화 완료! 마우스를 지역에 올려보세요.';

            }} catch (error) {{
                console.error("❌ 맵 데이터 로드 또는 맵 표시 중 오류 발생:", error);
                statusMessage.style.backgroundColor = '#fee2e2';
                statusMessage.style.borderColor = '#fca5a5';
                statusMessage.style.color = '#991b1b';
                statusMessage.innerHTML = '❌ 오류: 지도 시각화 실패. 상세 오류: ' + error.message;
            }}
        }}

        // Colab 환경 최적화를 위한 지연 없는 즉시 실행
        setTimeout(loadAndDisplayMapData, 0);
    </script>
</body>
</html>
"""

display(HTML(html_template))